spring.application.name=monitoring-service

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
spring.sql.init.platform=postgres

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1

# RabbitMQ Configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}

# Queue names
rabbitmq.queue.device.data=device_data
rabbitmq.exchange.sync=sync_exchange
rabbitmq.routing.key.device=device.created
rabbitmq.routing.key.user=user.created

websocket.service.url=http://websocket-service:8086/api/send-notification
device.service.url=http://device-service:8083/devices/intern

###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.address=0.0.0.0
server.port=${PORT:8080}
