spring.application.name=customer-support-service

# URL-ul Microserviciului de WebSocket
websocket.service.url=http://websocket-service:8086/api/send-chat

# Configurare Gemini
gemini.api.key=AIzaSyDfiO3PYLzgEKUrRwuQzvi9VPBp5iqXwm8
###gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
###gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.address=0.0.0.0
server.port=${PORT:8080}
