spring.application.name=device-service


###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
#database.ip = ${DB_IP:localhost}
#database.port = ${DB_PORT:5432}
#database.Device = ${DB_Device:tomarm}
#database.password = ${DB_PASSWORD:***}
#database.name = ${DB_DBNAME:DS_EMS}

spring.sql.init.platform=postgres
#spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
#spring.datasource.Devicename = ${database.Device}
#spring.datasource.password = ${database.password}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.Devicename=${SPRING_DATASOURCE_DeviceNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# RabbitMQ Configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}

# Synchronization Settings
rabbitmq.queue.user.sync=user_sync_queue
rabbitmq.exchange.sync=sync_exchange
rabbitmq.routing.key.user=user.created

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1

# Security
#spring.security.user.name=tomarm
#spring.security.user.password=tomarm
#spring.security.user.roles=ADMIN
#spring.security.user.roles=CLIENT
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.address=0.0.0.0
server.port=${PORT:8080}
